# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analyticsProContent.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61nalyticsProContent.proto\x12\x0crv.analytics\"\xb6\x01\n\nProContent\x12:\n\tmedia_bin\x18\x01 \x01(\x0b\x32%.rv.analytics.ProContent.ViewMediaBinH\x00\x12\x35\n\x08\x64ownload\x18\x02 \x01(\x0b\x32!.rv.analytics.ProContent.DownloadH\x00\x1a\x0e\n\x0cViewMediaBin\x1a\x1c\n\x08\x44ownload\x12\x10\n\x08is_retry\x18\x01 \x01(\x08\x42\x07\n\x05\x45ventb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analyticsProContent_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PROCONTENT']._serialized_start=44
  _globals['_PROCONTENT']._serialized_end=226
  _globals['_PROCONTENT_VIEWMEDIABIN']._serialized_start=173
  _globals['_PROCONTENT_VIEWMEDIABIN']._serialized_end=187
  _globals['_PROCONTENT_DOWNLOAD']._serialized_start=189
  _globals['_PROCONTENT_DOWNLOAD']._serialized_end=217
# @@protoc_insertion_point(module_scope)
