# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analyticsUpdate.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61nalyticsUpdate.proto\x12\x0crv.analytics\"\x8d\x02\n\x06Update\x12\x33\n\tdowngrade\x18\x01 \x01(\x0b\x32\x1e.rv.analytics.Update.DowngradeH\x00\x1a\xc3\x01\n\tDowngrade\x12I\n\x11\x66rom_version_type\x18\x01 \x01(\x0e\x32..rv.analytics.Update.Downgrade.FromVersionType\"k\n\x0f\x46romVersionType\x12\x1d\n\x19\x46ROM_VERSION_TYPE_UNKNOWN\x10\x00\x12\x1a\n\x16\x46ROM_VERSION_TYPE_BETA\x10\x01\x12\x1d\n\x19\x46ROM_VERSION_TYPE_RELEASE\x10\x02\x42\x08\n\x06\x41\x63tionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analyticsUpdate_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_UPDATE']._serialized_start=40
  _globals['_UPDATE']._serialized_end=309
  _globals['_UPDATE_DOWNGRADE']._serialized_start=104
  _globals['_UPDATE_DOWNGRADE']._serialized_end=299
  _globals['_UPDATE_DOWNGRADE_FROMVERSIONTYPE']._serialized_start=192
  _globals['_UPDATE_DOWNGRADE_FROMVERSIONTYPE']._serialized_end=299
# @@protoc_insertion_point(module_scope)
