# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analyticsTimecode.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61nalyticsTimecode.proto\x12\x0crv.analytics\"\xa5\x02\n\x08Timecode\x12\x31\n\x07startup\x18\x01 \x01(\x0b\x32\x1e.rv.analytics.Timecode.StartupH\x00\x12\x33\n\x08\x61\x63tivate\x18\x02 \x01(\x0b\x32\x1f.rv.analytics.Timecode.ActivateH\x00\x1aX\n\x07Startup\x12\x1b\n\x13is_input_configured\x18\x01 \x01(\x08\x12\x12\n\nis_enabled\x18\x02 \x01(\x08\x12\x1c\n\x14is_playlist_selected\x18\x03 \x01(\x08\x1aN\n\x08\x41\x63tivate\x12\x1b\n\x13playlist_item_count\x18\x01 \x01(\x05\x12\x11\n\tcue_count\x18\x02 \x01(\x05\x12\x12\n\nis_startup\x18\x03 \x01(\x08\x42\x07\n\x05\x45ventb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analyticsTimecode_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TIMECODE']._serialized_start=42
  _globals['_TIMECODE']._serialized_end=335
  _globals['_TIMECODE_STARTUP']._serialized_start=158
  _globals['_TIMECODE_STARTUP']._serialized_end=246
  _globals['_TIMECODE_ACTIVATE']._serialized_start=248
  _globals['_TIMECODE_ACTIVATE']._serialized_end=326
# @@protoc_insertion_point(module_scope)
