# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analyticsPlaybackMarker.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x61nalyticsPlaybackMarker.proto\x12\x0crv.analytics\"\xe7\x01\n\x0ePlaybackMarker\x12;\n\x06\x63reate\x18\x01 \x01(\x0b\x32).rv.analytics.PlaybackMarker.CreateMarkerH\x00\x1a\x8e\x01\n\x0c\x43reateMarker\x12\x44\n\x08location\x18\x01 \x01(\x0e\x32\x32.rv.analytics.PlaybackMarker.CreateMarker.Location\"8\n\x08Location\x12\x16\n\x12LOCATION_INSPECTOR\x10\x00\x12\x14\n\x10LOCATION_SIDEBAR\x10\x01\x42\x07\n\x05\x45ventb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analyticsPlaybackMarker_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PLAYBACKMARKER']._serialized_start=48
  _globals['_PLAYBACKMARKER']._serialized_end=279
  _globals['_PLAYBACKMARKER_CREATEMARKER']._serialized_start=128
  _globals['_PLAYBACKMARKER_CREATEMARKER']._serialized_end=270
  _globals['_PLAYBACKMARKER_CREATEMARKER_LOCATION']._serialized_start=214
  _globals['_PLAYBACKMARKER_CREATEMARKER_LOCATION']._serialized_end=270
# @@protoc_insertion_point(module_scope)
