# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analyticsSync.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61nalyticsSync.proto\x12\x0crv.analytics\"\xc8\x02\n\x04Sync\x12)\n\x05local\x18\x01 \x01(\x0b\x32\x18.rv.analytics.Sync.LocalH\x00\x1a\x88\x02\n\x05Local\x12\x34\n\tsync_type\x18\x01 \x01(\x0e\x32!.rv.analytics.Sync.Local.SyncType\x12\x17\n\x0finclude_library\x18\x02 \x01(\x08\x12\x15\n\rinclude_media\x18\x03 \x01(\x08\x12\x19\n\x11include_playlists\x18\x04 \x01(\x08\x12\x16\n\x0einclude_themes\x18\x05 \x01(\x08\x12\x1d\n\x15include_support_files\x18\x06 \x01(\x08\x12\x15\n\rreplace_files\x18\x07 \x01(\x08\"0\n\x08SyncType\x12\x10\n\x0cSYNC_TYPE_UP\x10\x00\x12\x12\n\x0eSYNC_TYPE_DOWN\x10\x01\x42\n\n\x08SyncTypeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analyticsSync_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SYNC']._serialized_start=38
  _globals['_SYNC']._serialized_end=366
  _globals['_SYNC_LOCAL']._serialized_start=90
  _globals['_SYNC_LOCAL']._serialized_end=354
  _globals['_SYNC_LOCAL_SYNCTYPE']._serialized_start=306
  _globals['_SYNC_LOCAL_SYNCTYPE']._serialized_end=354
# @@protoc_insertion_point(module_scope)
