# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analyticsCreate.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61nalyticsCreate.proto\x12\x0crv.analytics\"\xe3\x08\n\x06\x43reate\x12/\n\x07library\x18\x01 \x01(\x0b\x32\x1c.rv.analytics.Create.LibraryH\x00\x12\x31\n\x08playlist\x18\x02 \x01(\x0b\x32\x1d.rv.analytics.Create.PlaylistH\x00\x12\x39\n\x0cpresentation\x18\x03 \x01(\x0b\x32!.rv.analytics.Create.PresentationH\x00\x12\x42\n\x11template_playlist\x18\x04 \x01(\x0b\x32%.rv.analytics.Create.TemplatePlaylistH\x00\x1a\xa0\x01\n\x07Library\x12\x33\n\x06source\x18\x01 \x01(\x0e\x32#.rv.analytics.Create.Library.Source\"`\n\x06Source\x12\x12\n\x0eSOURCE_UNKNOWN\x10\x00\x12\x1b\n\x17SOURCE_APPLICATION_MENU\x10\x01\x12%\n!SOURCE_LIBRARY_OUTLINE_ADD_BUTTON\x10\x02\x1a\xcc\x02\n\x08Playlist\x12\x34\n\x06source\x18\x01 \x01(\x0e\x32$.rv.analytics.Create.Playlist.Source\x12\x30\n\x04type\x18\x02 \x01(\x0e\x32\".rv.analytics.Create.Playlist.Type\"`\n\x06Source\x12\x12\n\x0eSOURCE_UNKNOWN\x10\x00\x12\x1b\n\x17SOURCE_APPLICATION_MENU\x10\x01\x12%\n!SOURCE_LIBRARY_OUTLINE_ADD_BUTTON\x10\x02\"v\n\x04Type\x12\x10\n\x0cTYPE_UNKNOWN\x10\x00\x12\x15\n\x11TYPE_PRESENTATION\x10\x01\x12\x18\n\x14TYPE_PLANNING_CENTER\x10\x02\x12\x0f\n\x0bTYPE_FOLDER\x10\x03\x12\x1a\n\x16TYPE_TEMPLATE_PLAYLIST\x10\x04\x1a\xe5\x01\n\x0cPresentation\x12\x38\n\x06source\x18\x01 \x01(\x0e\x32(.rv.analytics.Create.Presentation.Source\"\x9a\x01\n\x06Source\x12\x12\n\x0eSOURCE_UNKNOWN\x10\x00\x12\x1b\n\x17SOURCE_APPLICATION_MENU\x10\x01\x12%\n!SOURCE_LIBRARY_OUTLINE_ADD_BUTTON\x10\x02\x12\x1c\n\x18SOURCE_DETAIL_ADD_BUTTON\x10\x03\x12\x1a\n\x16SOURCE_UNLINKED_HEADER\x10\x04\x1a\x8e\x01\n\x10TemplatePlaylist\x12\x18\n\x10total_item_count\x18\x01 \x01(\x05\x12\x14\n\x0cheader_count\x18\x02 \x01(\x05\x12\x19\n\x11placeholder_count\x18\x03 \x01(\x05\x12\x1a\n\x12presentation_count\x18\x04 \x01(\x05\x12\x13\n\x0bmedia_count\x18\x05 \x01(\x05\x42\x0b\n\tComponentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analyticsCreate_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREATE']._serialized_start=40
  _globals['_CREATE']._serialized_end=1163
  _globals['_CREATE_LIBRARY']._serialized_start=278
  _globals['_CREATE_LIBRARY']._serialized_end=438
  _globals['_CREATE_LIBRARY_SOURCE']._serialized_start=342
  _globals['_CREATE_LIBRARY_SOURCE']._serialized_end=438
  _globals['_CREATE_PLAYLIST']._serialized_start=441
  _globals['_CREATE_PLAYLIST']._serialized_end=773
  _globals['_CREATE_PLAYLIST_SOURCE']._serialized_start=342
  _globals['_CREATE_PLAYLIST_SOURCE']._serialized_end=438
  _globals['_CREATE_PLAYLIST_TYPE']._serialized_start=655
  _globals['_CREATE_PLAYLIST_TYPE']._serialized_end=773
  _globals['_CREATE_PRESENTATION']._serialized_start=776
  _globals['_CREATE_PRESENTATION']._serialized_end=1005
  _globals['_CREATE_PRESENTATION_SOURCE']._serialized_start=851
  _globals['_CREATE_PRESENTATION_SOURCE']._serialized_end=1005
  _globals['_CREATE_TEMPLATEPLAYLIST']._serialized_start=1008
  _globals['_CREATE_TEMPLATEPLAYLIST']._serialized_end=1150
# @@protoc_insertion_point(module_scope)
