# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analyticsTimeline.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61nalyticsTimeline.proto\x12\x0crv.analytics\"\xae\x05\n\x08Timeline\x12\x38\n\x0btrigger_cue\x18\x01 \x01(\x0b\x32!.rv.analytics.Timeline.TriggerCueH\x00\x12/\n\x06\x61\x63tion\x18\x02 \x01(\x0b\x32\x1d.rv.analytics.Timeline.ActionH\x00\x12\x36\n\nrecord_cue\x18\x03 \x01(\x0b\x32 .rv.analytics.Timeline.RecordCueH\x00\x1a\xcd\x02\n\nTriggerCue\x12\x43\n\x0ctrigger_type\x18\x01 \x01(\x0e\x32-.rv.analytics.Timeline.TriggerCue.TriggerType\x12\x45\n\rtiming_source\x18\x02 \x01(\x0e\x32..rv.analytics.Timeline.TriggerCue.TimingSource\"n\n\x0bTriggerType\x12\x16\n\x12TRIGGER_TYPE_SLIDE\x10\x00\x12\x16\n\x12TRIGGER_TYPE_MEDIA\x10\x01\x12\x16\n\x12TRIGGER_TYPE_AUDIO\x10\x02\x12\x17\n\x13TRIGGER_TYPE_ACTION\x10\x03\"C\n\x0cTimingSource\x12\x1a\n\x16TIMING_SOURCE_INTERNAL\x10\x00\x12\x17\n\x13TIMING_SOURCE_SMPTE\x10\x01\x1a\x98\x01\n\x06\x41\x63tion\x12=\n\x0b\x61\x63tion_type\x18\x01 \x01(\x0e\x32(.rv.analytics.Timeline.Action.ActionType\"O\n\nActionType\x12\x14\n\x10\x41\x43TION_TYPE_PLAY\x10\x00\x12\x14\n\x10\x41\x43TION_TYPE_STOP\x10\x01\x12\x15\n\x11\x41\x43TION_TYPE_RESET\x10\x02\x1a\x0b\n\tRecordCueB\x07\n\x05\x45ventb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analyticsTimeline_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TIMELINE']._serialized_start=42
  _globals['_TIMELINE']._serialized_end=728
  _globals['_TIMELINE_TRIGGERCUE']._serialized_start=218
  _globals['_TIMELINE_TRIGGERCUE']._serialized_end=551
  _globals['_TIMELINE_TRIGGERCUE_TRIGGERTYPE']._serialized_start=372
  _globals['_TIMELINE_TRIGGERCUE_TRIGGERTYPE']._serialized_end=482
  _globals['_TIMELINE_TRIGGERCUE_TIMINGSOURCE']._serialized_start=484
  _globals['_TIMELINE_TRIGGERCUE_TIMINGSOURCE']._serialized_end=551
  _globals['_TIMELINE_ACTION']._serialized_start=554
  _globals['_TIMELINE_ACTION']._serialized_end=706
  _globals['_TIMELINE_ACTION_ACTIONTYPE']._serialized_start=627
  _globals['_TIMELINE_ACTION_ACTIONTYPE']._serialized_end=706
  _globals['_TIMELINE_RECORDCUE']._serialized_start=708
  _globals['_TIMELINE_RECORDCUE']._serialized_end=719
# @@protoc_insertion_point(module_scope)
