# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analyticsWHMStore.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61nalyticsWHMStore.proto\x12\x0crv.analytics\"\x99\x01\n\x08WHMStore\x12\x36\n\nview_store\x18\x01 \x01(\x0b\x32 .rv.analytics.WHMStore.ViewStoreH\x00\x12\x33\n\x08\x64ownload\x18\x02 \x01(\x0b\x32\x1f.rv.analytics.WHMStore.DownloadH\x00\x1a\x0b\n\tViewStore\x1a\n\n\x08\x44ownloadB\x07\n\x05\x45ventb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analyticsWHMStore_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_WHMSTORE']._serialized_start=42
  _globals['_WHMSTORE']._serialized_end=195
  _globals['_WHMSTORE_VIEWSTORE']._serialized_start=163
  _globals['_WHMSTORE_VIEWSTORE']._serialized_end=174
  _globals['_WHMSTORE_DOWNLOAD']._serialized_start=176
  _globals['_WHMSTORE_DOWNLOAD']._serialized_end=186
# @@protoc_insertion_point(module_scope)
