# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: applicationInfo.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import version_pb2 as version__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61pplicationInfo.proto\x12\x07rv.data\x1a\rversion.proto\"\xc4\x03\n\x0f\x41pplicationInfo\x12\x33\n\x08platform\x18\x01 \x01(\x0e\x32!.rv.data.ApplicationInfo.Platform\x12*\n\x10platform_version\x18\x02 \x01(\x0b\x32\x10.rv.data.Version\x12\x39\n\x0b\x61pplication\x18\x03 \x01(\x0e\x32$.rv.data.ApplicationInfo.Application\x12-\n\x13\x61pplication_version\x18\x04 \x01(\x0b\x32\x10.rv.data.Version\"L\n\x08Platform\x12\x16\n\x12PLATFORM_UNDEFINED\x10\x00\x12\x12\n\x0ePLATFORM_MACOS\x10\x01\x12\x14\n\x10PLATFORM_WINDOWS\x10\x02\"\x97\x01\n\x0b\x41pplication\x12\x19\n\x15\x41PPLICATION_UNDEFINED\x10\x00\x12\x1c\n\x18\x41PPLICATION_PROPRESENTER\x10\x01\x12\x13\n\x0f\x41PPLICATION_PVP\x10\x02\x12\x1e\n\x1a\x41PPLICATION_PROVIDEOSERVER\x10\x03\x12\x1a\n\x16\x41PPLICATION_SCOREBOARD\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'applicationInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_APPLICATIONINFO']._serialized_start=50
  _globals['_APPLICATIONINFO']._serialized_end=502
  _globals['_APPLICATIONINFO_PLATFORM']._serialized_start=272
  _globals['_APPLICATIONINFO_PLATFORM']._serialized_end=348
  _globals['_APPLICATIONINFO_APPLICATION']._serialized_start=351
  _globals['_APPLICATIONINFO_APPLICATION']._serialized_end=502
# @@protoc_insertion_point(module_scope)
