# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: collectionElementType.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import uuid_pb2 as uuid__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x63ollectionElementType.proto\x12\x07rv.data\x1a\nuuid.proto\"\x91\x01\n\x15\x43ollectionElementType\x12%\n\x0eparameter_uuid\x18\x01 \x01(\x0b\x32\r.rv.data.UUID\x12\x16\n\x0eparameter_name\x18\x02 \x01(\t\x12\x39\n\x11parent_collection\x18\x03 \x01(\x0b\x32\x1e.rv.data.CollectionElementTypeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'collectionElementType_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_COLLECTIONELEMENTTYPE']._serialized_start=53
  _globals['_COLLECTIONELEMENTTYPE']._serialized_end=198
# @@protoc_insertion_point(module_scope)
