# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fileProperties.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import url_pb2 as url__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x66ileProperties.proto\x12\x07rv.data\x1a\turl.proto\"\xff\x01\n\x0e\x46ileProperties\x12\x1f\n\tlocal_url\x18\x01 \x01(\x0b\x32\x0c.rv.data.URL\x12\x43\n\x11remote_properties\x18\x02 \x01(\x0b\x32(.rv.data.FileProperties.RemoteProperties\x1a\x86\x01\n\x10RemoteProperties\x12G\n\nprocontent\x18\x01 \x01(\x0b\x32\x33.rv.data.FileProperties.RemoteProperties.ProContent\x1a)\n\nProContent\x12\x1b\n\x13\x64ownload_identifier\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fileProperties_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FILEPROPERTIES']._serialized_start=45
  _globals['_FILEPROPERTIES']._serialized_end=300
  _globals['_FILEPROPERTIES_REMOTEPROPERTIES']._serialized_start=166
  _globals['_FILEPROPERTIES_REMOTEPROPERTIES']._serialized_end=300
  _globals['_FILEPROPERTIES_REMOTEPROPERTIES_PROCONTENT']._serialized_start=259
  _globals['_FILEPROPERTIES_REMOTEPROPERTIES_PROCONTENT']._serialized_end=300
# @@protoc_insertion_point(module_scope)
