# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: musicKeyScale.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13musicKeyScale.proto\x12\x07rv.data\"\xf6\x04\n\rMusicKeyScale\x12\x32\n\tmusic_key\x18\x01 \x01(\x0e\x32\x1f.rv.data.MusicKeyScale.MusicKey\x12\x36\n\x0bmusic_scale\x18\x02 \x01(\x0e\x32!.rv.data.MusicKeyScale.MusicScale\"\xbc\x03\n\x08MusicKey\x12\x14\n\x10MUSIC_KEY_A_FLAT\x10\x00\x12\x0f\n\x0bMUSIC_KEY_A\x10\x01\x12\x15\n\x11MUSIC_KEY_A_SHARP\x10\x02\x12\x14\n\x10MUSIC_KEY_B_FLAT\x10\x03\x12\x0f\n\x0bMUSIC_KEY_B\x10\x04\x12\x15\n\x11MUSIC_KEY_B_SHARP\x10\x05\x12\x14\n\x10MUSIC_KEY_C_FLAT\x10\x06\x12\x0f\n\x0bMUSIC_KEY_C\x10\x07\x12\x15\n\x11MUSIC_KEY_C_SHARP\x10\x08\x12\x14\n\x10MUSIC_KEY_D_FLAT\x10\t\x12\x0f\n\x0bMUSIC_KEY_D\x10\n\x12\x15\n\x11MUSIC_KEY_D_SHARP\x10\x0b\x12\x14\n\x10MUSIC_KEY_E_FLAT\x10\x0c\x12\x0f\n\x0bMUSIC_KEY_E\x10\r\x12\x15\n\x11MUSIC_KEY_E_SHARP\x10\x0e\x12\x14\n\x10MUSIC_KEY_F_FLAT\x10\x0f\x12\x0f\n\x0bMUSIC_KEY_F\x10\x10\x12\x15\n\x11MUSIC_KEY_F_SHARP\x10\x11\x12\x14\n\x10MUSIC_KEY_G_FLAT\x10\x12\x12\x0f\n\x0bMUSIC_KEY_G\x10\x13\x12\x15\n\x11MUSIC_KEY_G_SHARP\x10\x14\":\n\nMusicScale\x12\x15\n\x11MUSIC_SCALE_MAJOR\x10\x00\x12\x15\n\x11MUSIC_SCALE_MINOR\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'musicKeyScale_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MUSICKEYSCALE']._serialized_start=33
  _globals['_MUSICKEYSCALE']._serialized_end=663
  _globals['_MUSICKEYSCALE_MUSICKEY']._serialized_start=159
  _globals['_MUSICKEYSCALE_MUSICKEY']._serialized_end=603
  _globals['_MUSICKEYSCALE_MUSICSCALE']._serialized_start=605
  _globals['_MUSICKEYSCALE_MUSICSCALE']._serialized_end=663
# @@protoc_insertion_point(module_scope)
