import proApiV1Identifier_pb2 as _proApiV1Identifier_pb2
import proApiV1MediaPlaylistItem_pb2 as _proApiV1MediaPlaylistItem_pb2
import proApiV1Playlist_pb2 as _proApiV1Playlist_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
