# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proApiV1Masks.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import proApiV1Identifier_pb2 as proApiV1Identifier__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proApiV1Masks.proto\x12\x07rv.data\x1a\x18proApiV1Identifier.proto\"\xa4\x02\n\x14\x41PI_v1_Masks_Request\x12\x34\n\x05masks\x18\x01 \x01(\x0b\x32#.rv.data.API_v1_Masks_Request.MasksH\x00\x12\x39\n\x08get_mask\x18\x02 \x01(\x0b\x32%.rv.data.API_v1_Masks_Request.GetMaskH\x00\x12\x43\n\rget_thumbnail\x18\x03 \x01(\x0b\x32*.rv.data.API_v1_Masks_Request.GetThumbnailH\x00\x1a\x07\n\x05Masks\x1a\x15\n\x07GetMask\x12\n\n\x02id\x18\x01 \x01(\t\x1a+\n\x0cGetThumbnail\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07quality\x18\x02 \x01(\x05\x42\t\n\x07Request\"\xe1\x02\n\x15\x41PI_v1_Masks_Response\x12\x35\n\x05masks\x18\x01 \x01(\x0b\x32$.rv.data.API_v1_Masks_Response.MasksH\x00\x12:\n\x08get_mask\x18\x02 \x01(\x0b\x32&.rv.data.API_v1_Masks_Response.GetMaskH\x00\x12\x44\n\rget_thumbnail\x18\x03 \x01(\x0b\x32+.rv.data.API_v1_Masks_Response.GetThumbnailH\x00\x1a\x32\n\x05Masks\x12)\n\x05masks\x18\x01 \x03(\x0b\x32\x1a.rv.data.API_v1_Identifier\x1a\x31\n\x07GetMask\x12&\n\x02id\x18\x01 \x01(\x0b\x32\x1a.rv.data.API_v1_Identifier\x1a\x1c\n\x0cGetThumbnail\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x42\n\n\x08Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proApiV1Masks_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_API_V1_MASKS_REQUEST']._serialized_start=59
  _globals['_API_V1_MASKS_REQUEST']._serialized_end=351
  _globals['_API_V1_MASKS_REQUEST_MASKS']._serialized_start=265
  _globals['_API_V1_MASKS_REQUEST_MASKS']._serialized_end=272
  _globals['_API_V1_MASKS_REQUEST_GETMASK']._serialized_start=274
  _globals['_API_V1_MASKS_REQUEST_GETMASK']._serialized_end=295
  _globals['_API_V1_MASKS_REQUEST_GETTHUMBNAIL']._serialized_start=297
  _globals['_API_V1_MASKS_REQUEST_GETTHUMBNAIL']._serialized_end=340
  _globals['_API_V1_MASKS_RESPONSE']._serialized_start=354
  _globals['_API_V1_MASKS_RESPONSE']._serialized_end=707
  _globals['_API_V1_MASKS_RESPONSE_MASKS']._serialized_start=564
  _globals['_API_V1_MASKS_RESPONSE_MASKS']._serialized_end=614
  _globals['_API_V1_MASKS_RESPONSE_GETMASK']._serialized_start=616
  _globals['_API_V1_MASKS_RESPONSE_GETMASK']._serialized_end=665
  _globals['_API_V1_MASKS_RESPONSE_GETTHUMBNAIL']._serialized_start=667
  _globals['_API_V1_MASKS_RESPONSE_GETTHUMBNAIL']._serialized_end=695
# @@protoc_insertion_point(module_scope)
