# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proApiV1ErrorResponse.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bproApiV1ErrorResponse.proto\x12\x07rv.data\"\xb3\x01\n\x15\x41PI_v1_Error_Response\x12?\n\x05\x65rror\x18\x01 \x01(\x0e\x32\x30.rv.data.API_v1_Error_Response.API_v1_Error_Type\"Y\n\x11\x41PI_v1_Error_Type\x12\r\n\tNOT_FOUND\x10\x00\x12\x0f\n\x0b\x42\x41\x44_REQUEST\x10\x01\x12\x12\n\x0eINTERNAL_ERROR\x10\x02\x12\x10\n\x0cUNAUTHORIZED\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proApiV1ErrorResponse_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_API_V1_ERROR_RESPONSE']._serialized_start=41
  _globals['_API_V1_ERROR_RESPONSE']._serialized_end=220
  _globals['_API_V1_ERROR_RESPONSE_API_V1_ERROR_TYPE']._serialized_start=131
  _globals['_API_V1_ERROR_RESPONSE_API_V1_ERROR_TYPE']._serialized_end=220
# @@protoc_insertion_point(module_scope)
