# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proApiV1Groups.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import proApiV1Color_pb2 as proApiV1Color__pb2
import proApiV1Identifier_pb2 as proApiV1Identifier__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proApiV1Groups.proto\x12\x07rv.data\x1a\x13proApiV1Color.proto\x1a\x18proApiV1Identifier.proto\"\xdd\x01\n\x15\x41PI_v1_Groups_Request\x12\x46\n\x0egroups_request\x18\x01 \x01(\x0b\x32,.rv.data.API_v1_Groups_Request.GroupsRequestH\x00\x12\x44\n\rtrigger_group\x18\x02 \x01(\x0b\x32+.rv.data.API_v1_Groups_Request.TriggerGroupH\x00\x1a\x0f\n\rGroupsRequest\x1a\x1a\n\x0cTriggerGroup\x12\n\n\x02id\x18\x01 \x01(\tB\t\n\x07Request\"\xea\x02\n\x16\x41PI_v1_Groups_Response\x12?\n\x06groups\x18\x01 \x01(\x0b\x32-.rv.data.API_v1_Groups_Response.GroupsRequestH\x00\x12\x45\n\rtrigger_group\x18\x02 \x01(\x0b\x32,.rv.data.API_v1_Groups_Response.TriggerGroupH\x00\x1a\xab\x01\n\rGroupsRequest\x12\x43\n\x06groups\x18\x01 \x03(\x0b\x32\x33.rv.data.API_v1_Groups_Response.GroupsRequest.Group\x1aU\n\x05Group\x12&\n\x02id\x18\x01 \x01(\x0b\x32\x1a.rv.data.API_v1_Identifier\x12$\n\x05\x63olor\x18\x02 \x01(\x0b\x32\x15.rv.data.API_v1_Color\x1a\x0e\n\x0cTriggerGroupB\n\n\x08Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proApiV1Groups_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_API_V1_GROUPS_REQUEST']._serialized_start=81
  _globals['_API_V1_GROUPS_REQUEST']._serialized_end=302
  _globals['_API_V1_GROUPS_REQUEST_GROUPSREQUEST']._serialized_start=248
  _globals['_API_V1_GROUPS_REQUEST_GROUPSREQUEST']._serialized_end=263
  _globals['_API_V1_GROUPS_REQUEST_TRIGGERGROUP']._serialized_start=265
  _globals['_API_V1_GROUPS_REQUEST_TRIGGERGROUP']._serialized_end=291
  _globals['_API_V1_GROUPS_RESPONSE']._serialized_start=305
  _globals['_API_V1_GROUPS_RESPONSE']._serialized_end=667
  _globals['_API_V1_GROUPS_RESPONSE_GROUPSREQUEST']._serialized_start=468
  _globals['_API_V1_GROUPS_RESPONSE_GROUPSREQUEST']._serialized_end=639
  _globals['_API_V1_GROUPS_RESPONSE_GROUPSREQUEST_GROUP']._serialized_start=554
  _globals['_API_V1_GROUPS_RESPONSE_GROUPSREQUEST_GROUP']._serialized_end=639
  _globals['_API_V1_GROUPS_RESPONSE_TRIGGERGROUP']._serialized_start=265
  _globals['_API_V1_GROUPS_RESPONSE_TRIGGERGROUP']._serialized_end=279
# @@protoc_insertion_point(module_scope)
