# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proApiV1Miscellaneous.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bproApiV1Miscellaneous.proto\x12\x07rv.data\"\x84\x01\n\x1c\x41PI_v1_Miscellaneous_Request\x12J\n\rfind_my_mouse\x18\x01 \x01(\x0b\x32\x31.rv.data.API_v1_Miscellaneous_Request.FindMyMouseH\x00\x1a\r\n\x0b\x46indMyMouseB\t\n\x07Request\"\x87\x01\n\x1d\x41PI_v1_Miscellaneous_Response\x12K\n\rfind_my_mouse\x18\x01 \x01(\x0b\x32\x32.rv.data.API_v1_Miscellaneous_Response.FindMyMouseH\x00\x1a\r\n\x0b\x46indMyMouseB\n\n\x08Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proApiV1Miscellaneous_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_API_V1_MISCELLANEOUS_REQUEST']._serialized_start=41
  _globals['_API_V1_MISCELLANEOUS_REQUEST']._serialized_end=173
  _globals['_API_V1_MISCELLANEOUS_REQUEST_FINDMYMOUSE']._serialized_start=149
  _globals['_API_V1_MISCELLANEOUS_REQUEST_FINDMYMOUSE']._serialized_end=162
  _globals['_API_V1_MISCELLANEOUS_RESPONSE']._serialized_start=176
  _globals['_API_V1_MISCELLANEOUS_RESPONSE']._serialized_end=311
  _globals['_API_V1_MISCELLANEOUS_RESPONSE_FINDMYMOUSE']._serialized_start=149
  _globals['_API_V1_MISCELLANEOUS_RESPONSE_FINDMYMOUSE']._serialized_end=162
# @@protoc_insertion_point(module_scope)
