# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proClockSource.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proClockSource.proto\x12\x07rv.data\"\xb5\x01\n\x0eProClockSource\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tconnected\x18\x03 \x01(\x08\x12\x0e\n\x06\x61\x63tive\x18\x04 \x01(\x08\x12*\n\x04type\x18\x05 \x01(\x0e\x32\x1c.rv.data.ProClockSource.Type\"8\n\x04Type\x12\x0f\n\x0bTYPE_UNKOWN\x10\x00\x12\x0e\n\nTYPE_INPUT\x10\x01\x12\x0f\n\x0bTYPE_OUTPUT\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proClockSource_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PROCLOCKSOURCE']._serialized_start=34
  _globals['_PROCLOCKSOURCE']._serialized_end=215
  _globals['_PROCLOCKSOURCE_TYPE']._serialized_start=159
  _globals['_PROCLOCKSOURCE_TYPE']._serialized_end=215
# @@protoc_insertion_point(module_scope)
