# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rv2d.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import graphicsData_pb2 as graphicsData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nrv2d.proto\x12\x07rv.data\x1a\x12graphicsData.proto\"\xc5\x01\n\x15IdentificationOverlay\x12\x13\n\x0bscreen_name\x18\x03 \x01(\t\x12\x36\n\x07outputs\x18\x01 \x03(\x0b\x32%.rv.data.IdentificationOverlay.Output\x1a_\n\x06Output\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\x12\x0c\n\x04name\x18\x05 \x01(\t\x12\x12\n\nframe_rate\x18\x06 \x01(\x01\"\xf2\x01\n\x1aLayerIdentificationOverlay\x12\x38\n\x05layer\x18\x01 \x01(\x0e\x32).rv.data.LayerIdentificationOverlay.Layer\x12\x12\n\nlayer_name\x18\x02 \x01(\t\"\x85\x01\n\x05Layer\x12\x15\n\x11LAYER_VIDEO_INPUT\x10\x00\x12\x0f\n\x0bLAYER_MEDIA\x10\x01\x12\x16\n\x12LAYER_PRESENTATION\x10\x02\x12\x17\n\x13LAYER_ANNOUNCEMENTS\x10\x03\x12\x0f\n\x0bLAYER_PROPS\x10\x04\x12\x12\n\x0eLAYER_MESSAGES\x10\x05\"\xf0\x01\n\tTextLayer\x12\x31\n\tcomposite\x18\x01 \x01(\x0b\x32\x1c.rv.data.TextLayer.CompositeH\x00\x12\x1f\n\x05media\x18\x02 \x01(\x0b\x32\x0e.rv.data.MediaH\x00\x12\x34\n\x07\x63ut_out\x18\x03 \x01(\x0b\x32!.rv.data.Graphics.Text.CutOutFillH\x00\x12?\n\x11\x62\x61\x63kground_effect\x18\x04 \x01(\x0b\x32\".rv.data.Graphics.BackgroundEffectH\x00\x1a\x0b\n\tCompositeB\x0b\n\tLayerTypeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rv2d_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IDENTIFICATIONOVERLAY']._serialized_start=44
  _globals['_IDENTIFICATIONOVERLAY']._serialized_end=241
  _globals['_IDENTIFICATIONOVERLAY_OUTPUT']._serialized_start=146
  _globals['_IDENTIFICATIONOVERLAY_OUTPUT']._serialized_end=241
  _globals['_LAYERIDENTIFICATIONOVERLAY']._serialized_start=244
  _globals['_LAYERIDENTIFICATIONOVERLAY']._serialized_end=486
  _globals['_LAYERIDENTIFICATIONOVERLAY_LAYER']._serialized_start=353
  _globals['_LAYERIDENTIFICATIONOVERLAY_LAYER']._serialized_end=486
  _globals['_TEXTLAYER']._serialized_start=489
  _globals['_TEXTLAYER']._serialized_end=729
  _globals['_TEXTLAYER_COMPOSITE']._serialized_start=705
  _globals['_TEXTLAYER_COMPOSITE']._serialized_end=716
# @@protoc_insertion_point(module_scope)
