# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: url.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\turl.proto\x12\x07rv.data\"\xfb\x07\n\x03URL\x12\'\n\x08platform\x18\x03 \x01(\x0e\x32\x15.rv.data.URL.Platform\x12\x19\n\x0f\x61\x62solute_string\x18\x01 \x01(\tH\x00\x12\x17\n\rrelative_path\x18\x02 \x01(\tH\x00\x12/\n\x05local\x18\x04 \x01(\x0b\x32\x1e.rv.data.URL.LocalRelativePathH\x01\x12\x35\n\x08\x65xternal\x18\x05 \x01(\x0b\x32!.rv.data.URL.ExternalRelativePathH\x01\x1a\xfb\x02\n\x11LocalRelativePath\x12\x31\n\x04root\x18\x01 \x01(\x0e\x32#.rv.data.URL.LocalRelativePath.Root\x12\x0c\n\x04path\x18\x02 \x01(\t\"\xa4\x02\n\x04Root\x12\x10\n\x0cROOT_UNKNOWN\x10\x00\x12\x14\n\x10ROOT_BOOT_VOLUME\x10\x01\x12\x12\n\x0eROOT_USER_HOME\x10\x02\x12\x17\n\x13ROOT_USER_DOCUMENTS\x10\x03\x12\x17\n\x13ROOT_USER_DOWNLOADS\x10\x04\x12\x13\n\x0fROOT_USER_MUSIC\x10\x05\x12\x16\n\x12ROOT_USER_PICTURES\x10\x06\x12\x14\n\x10ROOT_USER_VIDEOS\x10\x07\x12\x15\n\x11ROOT_USER_DESKTOP\x10\x0b\x12\x19\n\x15ROOT_USER_APP_SUPPORT\x10\x08\x12\x0f\n\x0bROOT_SHARED\x10\t\x12\r\n\tROOT_SHOW\x10\n\x12\x19\n\x15ROOT_CURRENT_RESOURCE\x10\x0c\x1a\xb5\x02\n\x14\x45xternalRelativePath\x12\x44\n\x05macos\x18\x01 \x01(\x0b\x32\x35.rv.data.URL.ExternalRelativePath.MacOSExternalVolume\x12\x44\n\x05win32\x18\x02 \x01(\x0b\x32\x35.rv.data.URL.ExternalRelativePath.Win32ExternalVolume\x12\x0c\n\x04path\x18\x03 \x01(\t\x1a*\n\x13MacOSExternalVolume\x12\x13\n\x0bvolume_name\x18\x01 \x01(\t\x1aW\n\x13Win32ExternalVolume\x12\x14\n\x0c\x64rive_letter\x18\x01 \x01(\t\x12\x13\n\x0bvolume_name\x18\x02 \x01(\t\x12\x15\n\rnetwork_share\x18\x03 \x01(\x08\"Z\n\x08Platform\x12\x14\n\x10PLATFORM_UNKNOWN\x10\x00\x12\x12\n\x0ePLATFORM_MACOS\x10\x01\x12\x12\n\x0ePLATFORM_WIN32\x10\x02\x12\x10\n\x0cPLATFORM_WEB\x10\x03\x42\t\n\x07StorageB\x12\n\x10RelativeFilePath\"\"\n\x04URLs\x12\x1a\n\x04urls\x18\x01 \x03(\x0b\x32\x0c.rv.data.URLb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'url_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_URL']._serialized_start=23
  _globals['_URL']._serialized_end=1042
  _globals['_URL_LOCALRELATIVEPATH']._serialized_start=228
  _globals['_URL_LOCALRELATIVEPATH']._serialized_end=607
  _globals['_URL_LOCALRELATIVEPATH_ROOT']._serialized_start=315
  _globals['_URL_LOCALRELATIVEPATH_ROOT']._serialized_end=607
  _globals['_URL_EXTERNALRELATIVEPATH']._serialized_start=610
  _globals['_URL_EXTERNALRELATIVEPATH']._serialized_end=919
  _globals['_URL_EXTERNALRELATIVEPATH_MACOSEXTERNALVOLUME']._serialized_start=788
  _globals['_URL_EXTERNALRELATIVEPATH_MACOSEXTERNALVOLUME']._serialized_end=830
  _globals['_URL_EXTERNALRELATIVEPATH_WIN32EXTERNALVOLUME']._serialized_start=832
  _globals['_URL_EXTERNALRELATIVEPATH_WIN32EXTERNALVOLUME']._serialized_end=919
  _globals['_URL_PLATFORM']._serialized_start=921
  _globals['_URL_PLATFORM']._serialized_end=1011
  _globals['_URLS']._serialized_start=1044
  _globals['_URLS']._serialized_end=1078
# @@protoc_insertion_point(module_scope)
