# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: userFeedback.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12userFeedback.proto\x12\x07rv.data\"\xfe\x05\n\x0cUserFeedback\x1a\xed\x05\n\x13\x41pplicationMetadata\x12\x1b\n\x13\x61pplication_version\x18\x01 \x01(\t\x12\x12\n\nos_version\x18\x02 \x01(\t\x12\\\n\x15\x61pplication_instances\x18\x03 \x03(\x0b\x32=.rv.data.UserFeedback.ApplicationMetadata.ApplicationInstance\x12i\n\"blackmagic_desktop_video_instances\x18\x04 \x03(\x0b\x32=.rv.data.UserFeedback.ApplicationMetadata.ApplicationInstance\x12\x41\n\x07screens\x18\x05 \x03(\x0b\x32\x30.rv.data.UserFeedback.ApplicationMetadata.Screen\x12\x1f\n\x17\x63rash_reporting_enabled\x18\x06 \x01(\x08\x12#\n\x1b\x61nalytics_reporting_enabled\x18\x07 \x01(\x08\x1a\x34\n\x13\x41pplicationInstance\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x1a\x9c\x02\n\x06Screen\x12\x0c\n\x04name\x18\x01 \x01(\t\x12O\n\nresolution\x18\x02 \x01(\x0b\x32;.rv.data.UserFeedback.ApplicationMetadata.Screen.Resolution\x12\x43\n\x04type\x18\x03 \x01(\x0e\x32\x35.rv.data.UserFeedback.ApplicationMetadata.Screen.Type\x12\x13\n\x0boutput_name\x18\x04 \x01(\t\x1a+\n\nResolution\x12\r\n\x05width\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\r\",\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08\x41UDIENCE\x10\x01\x12\t\n\x05STAGE\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'userFeedback_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERFEEDBACK']._serialized_start=32
  _globals['_USERFEEDBACK']._serialized_end=798
  _globals['_USERFEEDBACK_APPLICATIONMETADATA']._serialized_start=49
  _globals['_USERFEEDBACK_APPLICATIONMETADATA']._serialized_end=798
  _globals['_USERFEEDBACK_APPLICATIONMETADATA_APPLICATIONINSTANCE']._serialized_start=459
  _globals['_USERFEEDBACK_APPLICATIONMETADATA_APPLICATIONINSTANCE']._serialized_end=511
  _globals['_USERFEEDBACK_APPLICATIONMETADATA_SCREEN']._serialized_start=514
  _globals['_USERFEEDBACK_APPLICATIONMETADATA_SCREEN']._serialized_end=798
  _globals['_USERFEEDBACK_APPLICATIONMETADATA_SCREEN_RESOLUTION']._serialized_start=709
  _globals['_USERFEEDBACK_APPLICATIONMETADATA_SCREEN_RESOLUTION']._serialized_end=752
  _globals['_USERFEEDBACK_APPLICATIONMETADATA_SCREEN_TYPE']._serialized_start=754
  _globals['_USERFEEDBACK_APPLICATIONMETADATA_SCREEN_TYPE']._serialized_end=798
# @@protoc_insertion_point(module_scope)
